# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.mx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sello', models.CharField(db_index=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=3, max_digits=9)),
                ('emisor_rfc', localflavor.mx.models.MXRFCField(db_index=True, max_length=13, verbose_name='RFC del emisor')),
                ('emisor_nombre', models.CharField(db_index=True, max_length=255, verbose_name='nombre del emisor')),
                ('receptor_rfc', localflavor.mx.models.MXRFCField(db_index=True, max_length=13, verbose_name='RFC del receptor')),
                ('receptor_nombre', models.CharField(db_index=True, max_length=255, verbose_name='nombre del receptor')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', localflavor.mx.models.MXRFCField(max_length=13, unique=True, verbose_name='RFC')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribuyentes', to='facturas.Cliente')),
            ],
        ),
    ]
