# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_auto_20170123_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='sello',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
