# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20170123_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='fecha_timbrado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de timbrado'),
            preserve_default=False,
        ),
    ]
