# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos')),
                ('tipo', models.CharField(max_length=64)),
                ('utilizado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('direccion', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='dirección')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='mensajes', to='mensajes.Destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Remitente',
            fields=[
                ('direccion', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='dirección')),
            ],
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Remitente'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mensajes.Mensaje'),
        ),
    ]
